"""
Main HTML report assembler for the CareConnect Local Quality Gate report.
"""

from .report_styles import CSS
from .report_controls import FILTER_BAR, LEGEND_BLOCK
from .report_scripts import FILTER_JS
from .report_sections import build_summary_table, build_sections


def _build_banner(context: dict) -> tuple[str, str]:
    """Return banner color and text based on gate result."""
    if context["failed"]:
        return (
            "#c0392b",
            "WARNING — One or more required checks failed. "
            "Fix the issues below before merging.",
        )
    return "#27ae60", "APPROVED — All required checks passed."


def build_html(context: dict) -> str:
    """
    Build the complete local HTML report with interactive filtering.

    Parameters
    ----------
    context : dict
        Report context produced by generate_report.py.

    Returns
    -------
    str
        Full HTML document.
    """
    banner_color, banner_text = _build_banner(context)
    summary_table = build_summary_table(context)
    sections_html = build_sections(context)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CareConnect Local Quality Gate Report</title>
    <style>{CSS}</style>
</head>
<body>

<h1>CareConnect Local Quality Gate Report</h1>

<div class="banner" style="background:{banner_color};">
    {banner_text}
</div>

<div class="info-card">
    <h3>Report Header</h3>
    <table class="info-table">
        <tr><td><strong>Generated (UTC)</strong></td>
            <td>{context["generated_at"]}</td></tr>
        <tr><td><strong>User</strong></td>
            <td>{context["scan_user"]}</td></tr>
        <tr><td><strong>Scan Root</strong></td>
            <td><code>{context["repo_root"]}</code></td></tr>
    </table>
</div>

{LEGEND_BLOCK}

{FILTER_BAR}

<h2 id="tool-results-summary">Tool Results Summary</h2>
{summary_table}

<div class="section-header">Enforced Tools</div>
{sections_html}

<footer>
    Generated by CareConnect Local Quality Gate &mdash; {context["generated_at"]}
</footer>

{FILTER_JS}
</body>
</html>"""
