-- Hiring & onboarding document digitization (#58)
-- Creates the tables backing FormDefinition and FormSubmission. Mirrors the JPA
-- entity annotations so environments using Flyway (without Hibernate auto-DDL)
-- provision the same schema.

CREATE TABLE IF NOT EXISTS form_definitions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_type           VARCHAR(64)  NOT NULL,
    version             VARCHAR(64)  NOT NULL,
    title               VARCHAR(255) NOT NULL,
    effective_date      DATE         NOT NULL,
    expiration_date     DATE,
    status              VARCHAR(32)  NOT NULL,
    source_form_number  VARCHAR(64),
    source_edition      VARCHAR(64),
    file_category       VARCHAR(64)  NOT NULL,
    schema_json         JSONB        NOT NULL,
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP,
    CONSTRAINT uk_form_definition_type_version UNIQUE (form_type, version)
);

CREATE TABLE IF NOT EXISTS form_submissions (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_definition_id       BIGINT      NOT NULL,
    form_type                VARCHAR(64) NOT NULL,
    form_version             VARCHAR(64) NOT NULL,
    owner_id                 BIGINT      NOT NULL,
    owner_type               VARCHAR(32) NOT NULL,
    patient_id               BIGINT,
    status                   VARCHAR(32) NOT NULL,
    field_values            JSONB,
    user_file_id             BIGINT,
    supporting_user_file_ids JSONB,
    submitted_at             TIMESTAMP,
    reviewed_by              BIGINT,
    reviewed_at              TIMESTAMP,
    created_at               TIMESTAMP   NOT NULL,
    updated_at               TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_form_submission_owner
    ON form_submissions (owner_id, owner_type);
CREATE INDEX IF NOT EXISTS idx_form_submission_definition
    ON form_submissions (form_definition_id);
CREATE INDEX IF NOT EXISTS idx_form_submission_user_file
    ON form_submissions (user_file_id);
