

-- Create vital_sample table for unified vital signs storage
CREATE TABLE vital_sample (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              patient_id BIGINT NOT NULL,
                              timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                              heart_rate DOUBLE PRECISION,
                              spo2 DOUBLE PRECISION,
                              systolic INTEGER,
                              diastolic INTEGER,
                              weight DOUBLE PRECISION,
                              mood_value INTEGER CHECK (mood_value >= 1 AND mood_value <= 10),
                              pain_value INTEGER CHECK (pain_value >= 1 AND pain_value <= 10),
                              created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                              CONSTRAINT fk_vital_sample_patient FOREIGN KEY (patient_id) REFERENCES patient(id) ON DELETE CASCADE
);


-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_vital_sample_patient_timestamp ON vital_sample(patient_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_vital_sample_timestamp ON vital_sample(timestamp);

