-- Add gender column to patient and caregiver tables

ALTER TABLE patient ADD COLUMN gender VARCHAR(20);
ALTER TABLE caregiver ADD COLUMN gender VARCHAR(20);

-- Create patient_allergy table for storing patient allergies

CREATE TABLE patient_allergy (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 patient_id BIGINT NOT NULL,
                                 allergen VARCHAR(255) NOT NULL,
                                 allergy_type VARCHAR(50),
                                 severity VARCHAR(50),
                                 reaction TEXT,
                                 notes TEXT,
                                 diagnosed_date VARCHAR(50),
                                 is_active BOOLEAN NOT NULL DEFAULT true,
                                 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 CONSTRAINT fk_patient_allergy_patient FOREIGN KEY (patient_id) REFERENCES patient(id) ON DELETE CASCADE
);
;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_patient_allergy_patient_id ON patient_allergy(patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_allergy_active ON patient_allergy(patient_id, is_active);
CREATE INDEX IF NOT EXISTS idx_patient_allergy_allergen ON patient_allergy(allergen);


-- Populate the patient_id column from existing data
UPDATE family_member_link fml
SET patient_id = (
    SELECT p.id
    FROM patient p
    WHERE p.user_id = fml.patient_user_id
);

-- Add index for faster queries
CREATE INDEX IF NOT EXISTS idx_family_member_link_patient_id ON family_member_link(patient_id);

-- Add comment
COMMENT ON COLUMN family_member_link.patient_id IS 'Denormalized patient ID for faster queries without joins';
COMMENT ON CONSTRAINT uk_family_member_link_unique ON family_member_link IS 'Prevents duplicate family member-patient links';
COMMENT ON CONSTRAINT uk_family_member_link_patient_unique ON family_member_link IS 'Prevents duplicate family member-patient links using patient_id';
